### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by devinrader** [dprothero/NgrokExtensions#1]
![image](https://cloud.githubusercontent.com/assets/1095289/19947850/51e79668-a120-11e6-9fa7-066fdd6a129a.png)

**Comment by dprothero** [comment]
This is what happens if you haven't installed ngrok first *or* ngrok.exe isn't in your PATH. If you install ngrok using Chocolatey, it does this for you.

**Comment by dprothero** [comment]
Leaving this issue open as it would be good to have a friendly error message for this situation.

**Comment by dprothero** [comment]
Fixed by #2
