### ISSUE TITLE
Install of extension incomplete (perhaps)

### ISSUE THREAD

**Issue by CosCallis** [dprothero/NgrokExtensions#21]
Following the installation of the ngrok plugin for VS2017 the appropriate menu option appears. However, when I select that menu option (Tools ->Start ngrok Tunnel)  I receive a message stating that it is not installed...and offering to do so.

![notinstalled](https://user-images.githubusercontent.com/35605325/35158768-ca9eca9c-fcfd-11e7-98cb-0858dda23544.png)

If I select Yes, I am then given a null reference exception:
![nullreference](https://user-images.githubusercontent.com/35605325/35158810-e6b2de44-fcfd-11e7-95f4-0d2f6a666609.png)

Installing plugins is pretty simple, I can't imagine what I might have done 'wrong' 

(also reported: https://stackoverflow.com/q/48334215/681009)

**Comment by russmeine** [comment]
Same.  VS 2017

**Comment by mnickhoo** [comment]
i problem too

**Comment by simonds** [comment]
As a quick fix, can I manually download ngrok.exe and drop it into a particular folder? I tried placing it in the extension folder, but that didn't help.

**Comment by VladislavAntonyuk** [comment]
You have to setup path to ngrok exe in VS

**Comment by simonds** [comment]
Found it in Options. Thanks @VladislavAntonyuk.

**Comment by SimonChris** [comment]
I am having the same problem.

**Comment by VladislavAntonyuk** [comment]
@SimonChris You have to setup path to ngrok exe in VS options

**Comment by skills0** [comment]
It would be helpful if the setting up the options was noted somewhere obvious. I am still getting the "Not installed" issue even if I set the path.

**Comment by VladislavAntonyuk** [comment]
Make sure you have set up path correctly. Try to copy ngrok.exe to C: driver and set the path as C:\ngrok.exe

**Comment by skills0** [comment]
ok, so the path needs to include the "ngrok.exe", which is different than the way most path hints work. working now. just feel like this needs slightly clearer documentation.

**Comment by mattxo** [comment]
I had to restart VS2017 after adding the PATH variable

**Comment by devinrader** [comment]
@dprothero wonder if this is the issue I also ran into with the regex being broken?

**Comment by dprothero** [comment]
Hey all, I will be working on fixing this and updating the documentation. Thanks for your patience. When it installs ngrok for you, it should set the path for you automatically. Something broke in the automated download process. 👎

**Comment by dprothero** [comment]
Proposed fix: https://github.com/dprothero/NgrokExtensions/pull/24

**Comment by dprothero** [comment]
Hey folks, just released v0.9.11 that should address this issue. However, feel free to re-open this issue if you find otherwise.
