### ISSUE TITLE
502 Bad Gateway The server returned an invalid or incomplete response

### ISSUE THREAD

**Issue by ImTrojanxx** [dprothero/NgrokExtensions#23]

**Comment by dprothero** [comment]
Can you confirm your web server project is actually running? This is usually the error that is returned when ngrok is running, but your server is _not_ running.

**Comment by dprothero** [comment]
Another reason we have found for this error is if you are using a new ASP.NET Core project that now defaults to `https`. whereas ngrok only works with `http`. If you change your project to turn off `https`, that should solve the issue. See this article:
https://stackoverflow.com/questions/46507029/how-to-disable-https-in-visual-studio-2017-web-proj-asp-net-core-2-0
