### ISSUE TITLE
ngrok 2.3.34 or above is not installed

### ISSUE THREAD

**Issue by sariyandath** [dprothero/NgrokExtensions#45]
When I click "start ngrok tunnel" from Visual studio 2019 (version 16.5.5), displaying  a message "ngrok 2.3.34 or above is not installed. Would you like me to download it from ngrok.com and install it for you. If I press Yes, got an error message: "Access to the path 'C:\windows\System32\ngrok.exe' is denied."

**Comment by 32x0lf** [comment]
I have experienced this one too and when I checked that Path there is no ngrok.exe in there.  Is there a way that we could update this one to the latest version? I am using VS2019 community and windows 10 pro.

**Comment by 32x0lf** [comment]
@sariyandath  I have fixed it by setting the Environment Variable  to the path where your ngrok.exe located. Once you have set the path. Restart the Visual studio and try again. Hope this helps.

**Comment by xiuCactus** [comment]
no it doesn't help
